version = 1
SPDX-PackageName = "file-link-executor"
SPDX-PackageSupplier = "Friedrich von Never <friedrich@fornever.me>"
SPDX-PackageDownloadLocation = "https://github.com/ForNeVeR/file-link-executor"

[[annotations]]
path = "**/.idea/**/**"
precedence = "override"
SPDX-FileCopyrightText = "2018-2026 Friedrich von Never <friedrich@fornever.me>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "gradle/wrapper/gradle-wrapper.jar",
    "gradle/wrapper/gradle-wrapper.properties"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Gradle authors <https://gradle.org/>"
SPDX-License-Identifier = "Apache-2.0"
