name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.config.image }}
    name: ${{ matrix.config.image }}
    strategy:
      matrix:
        config:
          - image: macos-latest
            jvmCache: '~/.local/share/gradle-jvm'
          - image: ubuntu-latest
            jvmCache: '~/.local/share/gradle-jvm'
          - image: windows-latest
            jvmCache: '~/AppData/Local/gradle-jvm'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ matrix.config.jvmCache }}
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble
        run: ./gradlew assemble

      - name: Stop Gradle daemon
        run: ./gradlew --stop
