# SPDX-FileCopyrightText: 2022-2026 Friedrich von Never <friedrich@fornever.me>
#
# SPDX-License-Identifier: MIT

name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: ${{ matrix.config.image }}
    name: ${{ matrix.config.image }}
    strategy:
      matrix:
        config:
          - image: macos-14
            jvmCache: '~/.local/share/gradle-jvm'
          - image: ubuntu-24.04
            jvmCache: '~/.local/share/gradle-jvm'
          - image: windows-2025
            jvmCache: '~/AppData/Local/gradle-jvm'
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ matrix.config.jvmCache }}
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew buildPlugin

      - name: Stop Gradle daemon
        run: ./gradlew --stop
  validation:
    runs-on: ubuntu-24.04
    name: "Validate Gradle wrapper"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  licenses:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the sources
        uses: actions/checkout@v6
      - name: REUSE license check
        uses: fsfe/reuse-action@v6
